### PR TITLE
Fix: Convert to JSX (fixes #238)

### LINKED ISSUE #238: Convert to JSX

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #238 

### Fix
* Converts .hbs template to .jsx
* #244 Progress dots - make non-interactive
* Add style for mobile instruction error. "In mobile view, highlight instruction if user navigates to another item before completing, in case the strapline is missed"
* No change to how touch/swipe controls work (jQuery).
* Replaced `user-drag` CSS property with `draggable` HTML property
* Checks the user's system `prefers-reduced-motion` preference and disables animations if necessary

### Dependencies
https://github.com/adaptlearning/adapt-contrib-vanilla/issues/398 Remove hover state styling from the progress indicators

### CODE REVIEW

**Comment by swashbuck** [comment]
Still outstanding:

- Move navigation labels to JSX. Will probably follow the format of https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/256
- Move button enabling/disabling to JSX

**Comment by swashbuck** [comment]
Ready for review.

**Comment by StuartNicholls** [comment]
@swashbuck I can see the pips are now no longer selectable but the hover states in the css are still there

**Comment by swashbuck** [comment]
> @swashbuck I can see the pips are now no longer selectable but the hover states in the css are still there

@StuartNicholls I've created https://github.com/adaptlearning/adapt-contrib-vanilla/issues/398 to remove the hover states.

File: templates/narrative.jsx [hunk 1]
```diff
@@ -0,0 +1,296 @@
...
+  });
+
+  const focusOnNarrativeElement = (itemIndex) => {
+    const dataIndexAttr = `[data-index='${itemIndex}']`;
+
+    const $elementToFocus = _isLargeMode ?
+      $(`.narrative__content-item${dataIndexAttr}`) :
+      $(`.narrative__strapline-btn${dataIndexAttr}`);
+
+    if ($elementToFocus.length) {
```
Comment (eleanor-heath) [inline templates/narrative.jsx:50]: opportunity to return early here
`if (!$elementToFocus.length) return;`

**Review by eleanor-heath — APPROVED** [review]

**Review by StuartNicholls — APPROVED** [review]

File: templates/narrative.jsx (hunk 1 above)
Comment (swashbuck) [reply templates/narrative.jsx]: Done

File: templates/narrative.jsx [hunk 2]
```diff
@@ -0,0 +1,296 @@
...
+
+    focusOnNarrativeElement(itemIndex);
+  });
+
+  const focusOnNarrativeElement = (itemIndex) => {
+    const dataIndexAttr = `[data-index='${itemIndex}']`;
+
+    const $elementToFocus = _isLargeMode ?
+      $(`.narrative__content-item${dataIndexAttr}`) :
+      $(`.narrative__strapline-btn${dataIndexAttr}`);
```
[the remark this answers is not in the document]
Comment (kirsty-hames) [reply templates/narrative.jsx:48]: I've just spotted an issue that might be related to this. On a page consisting of multiple Narratives, when I interact with the `.narrative__controls` and the item in view updates, focus jumps me to a Narrative instance that precedes on the page. It's a global issue as I can replicate across browsers/devices.

File: less/narrative.less [hunk 3]
```diff
@@ -1,5 +1,16 @@
 .narrative {
-  &:not(.items-are-full-width) &__content {
+  &__instruction-inner.instruction-error {
+    color: @validation-error;
+    .icon;
+    .icon-exclamation;
```
Comment (kirsty-hames) [inline less/narrative.less:5]: As per https://github.com/adaptlearning/adapt-contrib-narrative/issues/248 (normalise icons globally) I'd suggest implementing this via the templates rather than CSS. The `aria-hidden` prevents pseudo elements being read by screen readers.
This would mean updating core however as this would need to be implemented in _component.hbs_. I'm not sure if we have a current need for icons in other component instruction text but I can see this being useful and by including it here would make it consistent across components.

File: templates/narrative.jsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (swashbuck) [reply templates/narrative.jsx]: Ok, I believe this is fixed now.

File: less/narrative.less (hunk 3 above)
Comment (swashbuck) [reply less/narrative.less]: @kirsty-hames Good callout. I've tagged you on a PR for this, so let me know what you think.

https://github.com/adaptlearning/adapt-contrib-core/pull/329

File: templates/narrative.jsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (kirsty-hames) [reply templates/narrative.jsx]: I can confirm fixed (testing on same spec above).

File: less/narrative.less (hunk 3 above)
Comment (swashbuck) [reply less/narrative.less]: Core #329 has been merged.

**Review by kirsty-hames — APPROVED** [review]
Tested on Mac Safari, FF and Chrome. Android tablet, iPhone and iPad. 
Screen reader tested with voiceOver.
