### PR TITLE
Fix: Narrative component registering as complete or partially complete before visiting (fixes #304)

### LINKED ISSUE #304: Item completion should be representative of visited items
### Subject of the issue
Since [progressive item completion](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/221) was introduced, Narrative progress displays as partially complete before the component is in view or interacted with. See screen shot of PLP drawer below on first entering a topic.

PLP_drawer

### Expected behaviour
Narrative has multiple layout options available with different completion criteria (in view or interaction). Item completion should be dependant on the following for each layout:

Default: Selecting `.narrative__controls` (for desktop) or `.narrative__strapline-btn` (for mobile).

`_hasNavigationInTextArea`: Selecting `.narrative__controls`.

`_isTextBelowImage` and  `_isMobileTextBelowImage`: Selecting `.narrative__controls` or each item display text being in view.

`_isStackedOnMobile`: Each item display text being in view.

### Actual behaviour
Regardless of layout, the first item is always complete (before in view or interaction).

### PR DESCRIPTION
**Pull request by lemmyadams**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #304 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Sets an inview toggle before registering an item as visited

### CODE REVIEW

File: js/NarrativeView.js [hunk 1]
```diff
@@ -25,6 +25,8 @@ class NarrativeView extends ComponentView {
 
     this.model.set('_isInitial', true);
     this.model.set('_activeItemIndex', 0);
+    this.model.set('_isInview', false);
+    this.model.set('_isFullyLoaded', false);
```
Comment (oliverfoster) [inline js/NarrativeView.js:29]:
```suggestion
    this_isFullyLoaded = false;
```
Would you mind changing both of these view states into view properties rather than model attributes? Then I can have a better look Tuesday/Wednesday if that's ok?

File: js/NarrativeView.js [hunk 2]
```diff
@@ -283,6 +284,22 @@ class NarrativeView extends ComponentView {
     }
   }
 
+  inview() {
+    if (this._isFullyLoaded === false) {
+      this._isFullyLoaded = true;
```
Comment (oliverfoster) [inline js/NarrativeView.js:289]: I don't understand why this is necessary. Are you expecting this function to run twice but on the first time just to signify that the component is fully loaded?

The inview callback has three arguments, and it will be called at various points to signify the inview state of the element. 

You can see the three arguments called to the inview callback function in the [core library](https://github.com/adaptlearning/adapt-contrib-core/blob/431df2931db2c41a08eceee904565e3e92077fbf/libraries/inview.js#L132-L139), this is how they look when the function is called https://github.com/adaptlearning/adapt-contrib-core/blob/431df2931db2c41a08eceee904565e3e92077fbf/js/views/componentView.js#L55-L76.

File: js/NarrativeView.js [hunk 3]
```diff
@@ -283,6 +284,22 @@ class NarrativeView extends ComponentView {
...
+      const activeItem = this.model.getActiveItem();
+      if (!!activeItem) {
+        activeItem.toggleVisited(true);
+        this.$('.component__widget').off('inview');
+      }
+
+      if (this.shouldUseInviewCompletion()) this.setupInviewCompletion('.component__widget');
+    }
+  }
+
```
[the remark this answers is not in the document]
Comment (lemmyadams) [reply js/NarrativeView.js]: Updated and working

File: js/NarrativeView.js [hunk 4]
```diff
@@ -351,10 +368,8 @@ class NarrativeView extends ComponentView {
     return true;
   }
 
-  setupEventListeners() {
-    if (!this.shouldUseInviewCompletion()) return;
-
-    this.setupInviewCompletion('.component__widget');
+  setupInviewVisited() {
+    this.$('.component__widget').on('inview', _.throttle(_.bind(this.inview, this), 100));
```
[the remark this answers is not in the document]
Comment (lemmyadams) [reply js/NarrativeView.js:371]: Wasn't sure which was better, but if Debounce is more appropriate I will change it to that

File: js/NarrativeView.js (hunk 2 above)
Comment (oliverfoster) [reply js/NarrativeView.js:289]:
```js
  onInview(event, isVisible) {
    if (!isVisible) return;
    // do stuff for when it's visible here
  }
```

**Comment by oliverfoster** [comment]
I'm testing this today, sorry for the wait.

**Comment by oliverfoster** [comment]
Nice code. 

I made a few minor changes. I opted to override `onInview` and call the super function, passing through the arguments, rather than setting up two separate inview listeners and callback functions. I've also removed some nesting and white space.

I've tested it with various page visits, revisits, resizing, swapping out for hotgraphic etc. I think it works as intended.

Thanks for this. :+1:

**Review by ethan-lp — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀
